openapi: 3.0.0
x-stoplight:
  id: 59lm0rrtsuds9
info:
  title: Api
  version: '1.0'
  contact:
    name: Aikintech
    url: www.aikintech.com
    email: admin@aikintech.com
  description: Adwaso API documentaion
servers:
  - url: 'http://localhost:10010'
    description: local
paths:
  /auth/login:
    post:
      summary: ''
      tags:
        - client
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
      operationId: auth-login
      description: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
  /auth/register:
    post:
      summary: ''
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
      operationId: auth-register
      description: Register user
      tags:
        - client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        description: ''
  /auth/verify-phone-number:
    post:
      summary: ''
      tags:
        - client
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyPhoneNumberResponse'
      operationId: auth-verify-phone-number
      description: Verify phone number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyPhoneNumberRequest'
  /auth/verify-otp:
    post:
      summary: ''
      tags:
        - client
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
      operationId: auth-verify-otp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOtpRequest'
      description: Verify OTP
components:
  schemas:
    RegisterRequest:
      type: object
      x-examples: {}
      properties:
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        phoneNumber:
          type: string
          x-stoplight:
            id: 1hmq03tf2a3n4
        countryCode:
          type: string
          x-stoplight:
            id: roxfrzfxqpvcl
        location:
          type: string
          x-stoplight:
            id: m1gvl1igauxxu
        dateOfBirth:
          type: string
          x-stoplight:
            id: khp36dwpes15a
      required:
        - firstName
        - lastName
        - password
        - phoneNumber
        - countryCode
        - location
        - dateOfBirth
    LoginRequest:
      title: LoginRequest
      x-stoplight:
        id: hked38o5zlizc
      type: object
      properties:
        phoneNumber:
          type: string
          x-stoplight:
            id: w36foii9i2c16
        password:
          type: string
          x-stoplight:
            id: w36foii9i2c16
        countryCode:
          type: string
          x-stoplight:
            id: gmcr2glvi8qlp
      required:
        - phoneNumber
        - password
        - countryCode
    MessageResponse:
      title: MessageResponse
      x-stoplight:
        id: iy1oryam38jhx
      type: object
      properties:
        message:
          type: string
          x-stoplight:
            id: 5hhl7tmezgi2y
    ValidationResponse:
      type: object
      x-examples:
        Example 1:
          errors:
            - field: phoneNumber
              reasons:
                - The phone number field is required.
            - field: countryCode
              reasons:
                - The country code field is required.
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              reasons:
                type: array
                items:
                  type: string
            required:
              - field
              - reasons
      required:
        - errors
    VerifyPhoneNumberRequest:
      title: VerifyPhoneNumberRequest
      x-stoplight:
        id: 2vgtbe5dqcbr3
      type: object
      properties:
        phoneNumber:
          type: string
          x-stoplight:
            id: v0qtwcy3lat3p
        countryCode:
          type: string
          x-stoplight:
            id: 9c7e86e6mrsdl
        sendOtp:
          type: boolean
          x-stoplight:
            id: c1itc5nu8pyhk
          default: false
      required:
        - phoneNumber
        - countryCode
        - sendOtp
    VerifyOtpRequest:
      title: VerifyOtpRequest
      x-stoplight:
        id: ft8l1uy5ejacg
      type: object
      properties:
        code:
          type: string
          x-stoplight:
            id: bj6uope0e0ibp
        phoneNumber:
          type: string
          x-stoplight:
            id: wq9oy7krkg9mo
        countryCode:
          type: string
          x-stoplight:
            id: 4rhxp5bpefkcg
      required:
        - code
        - phoneNumber
        - countryCode
      description: ''
    VerifyPhoneNumberResponse:
      type: object
      x-examples:
        Example 1:
          message: Phone number verified successfully.
          userId: ''
      properties:
        message:
          type: string
        userId:
          type: string
      required:
        - message
        - userId
    LoginResponse:
      type: object
      x-examples:
        Example 1:
          tokens:
            access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY5Nzg0NDgsImlhdCI6MTcwNjk3NzI0OCwiaXNzIjoiQWR3YXNvIiwic3ViIjoibTk0bjh1VkN4WDFlIiwidG9rZW5UeXBlIjoiYWNjZXNzIn0.n5stiaBiMU5_KV1yT7ht71eRX4YWzRXOBQawOwOabAI
            refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcwNjM2NDgsImlhdCI6MTcwNjk3NzI0OCwiaXNzIjoiQWR3YXNvIiwic3ViIjoibTk0bjh1VkN4WDFlIiwidG9rZW5UeXBlIjoicmVmcmVzaCJ9.mxcS68PSOHOYSCnb9YVO320Zay_WF8t5nkkY-7dseUY
          user:
            avatar: 'https://ui-avatars.com/api/?name=John+Doe&background=random&color=fff'
            firstName: John
            lastName: Doe
      properties:
        tokens:
          type: object
          required:
            - access
            - refresh
          properties:
            access:
              type: string
            refresh:
              type: string
        user:
          type: object
          required:
            - avatar
            - firstName
            - lastName
          properties:
            avatar:
              type: string
            firstName:
              type: string
            lastName:
              type: string
      required:
        - tokens
        - user
  securitySchemes:
    X-API-KEY:
      name: API Key
      type: apiKey
      in: header
    X-SHOP-DOMAIN:
      name: Subdomain Key
      type: apiKey
      in: header
      description: ''
tags:
  - name: backoffice
  - name: client
